### ISSUE TITLE
Translate Bug on Zoom In

### ISSUE THREAD

**Issue by sentar** [SunboX/ST2_ImageViewer#1]
If a inital scaled down image is zoomed to a scale, that there is still a translateX/Y needed, the image will be cropped on the other side.

Problem: Not correct sized figEl
Solution: A change in #adjustScroller
...
var boundWidth = Math.max(me.imgWidth \* scale, me.viewportWidth);
var boundHeight = Math.max(me.imgHeight \* scale, me.viewportHeight);

to 

var boundWidth = Math.max(me.imgWidth \* scale + 2 \* me.translateX, me.viewportWidth);
var boundHeight = Math.max(me.imgHeight \* scale + 2 \* me.translateY, me.viewportHeight);

**Comment by SunboX** [comment]
Thx, will check it this evening. :o)
